<?php


?>
<!DOCTYPE html>
<html class="no-js">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<base href="<?= $this->Application->Config->System->Web->base_url ?>admin/" />

	<title>Admin Panel<?= ((isset($this->Title) && trim($this->Title) != '') ? ' - '.$this->Title : '') ?></title>
	
	<link rel="stylesheet" type="text/css" href="../css/reset.css" />
	<link rel="stylesheet" type="text/css" href="css/style.css" />
	<?= $this->GetStyleSheets() ?>

	<script type="text/javascript" src="../js/lib/modernizer.min.js"></script>
	<script type="text/javascript" src="../js/lib/jquery.min.js"></script>
	<script type="text/javascript" src="../js/site.js"></script>
	<script type="text/javascript" src="../js/admin.js"></script>
	<?= $this->GetJSFiles() ?>
	
	<?= $this->GetStyles() ?>
</head>
<body>
	<?=$this->GetContent('default')?>
</body>
</html>