<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<base href="<?= $this->App->Config->Site->base_url ?>" />

	<title><?= ((isset($this->Title) && trim($this->Title) != '') ? ' - '.$this->Title : '') ?></title>

	<link rel="stylesheet" type="text/css" href="css/reset.css" />
	<link rel="stylesheet" type="text/css" href="css/debug.css" />
	<?= $this->GetStyleSheets() ?>

	<script type="text/javascript" src="js/lib/jquery.min.js"></script>
	<?= $this->GetJSFiles() ?>

	<?= $this->GetStyles() ?>
</head>
<body>
	<section class="wrapper">
		<header>
			<img class="logo" src="http://thisguys.com/images/logo.png">
			<nav>
				<ul>
					<li><a href="debug/">Dashboard</a></li>
					<li><a href="debug/errors/">Errors</a></li>
					<li><a href="debug/config">Config</a></li>
					<li><a href="debug/db/">DB</a></li>
					<li><a href="debug/session/">Session</a></li>
				</ul>
			</nav>
		</header>
<?= $this->GetContent('default') ?>
		<footer>
			&copy; ThisGuys Development - All Rights Reserved
		</footer>
	</section>
</body>
</html>