<?php declare(strict_types=1); ?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /> 
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />

	<title><?= $this->App->Config->Site->title . ((isset($this->Title) && trim($this->Title) != '') ? ' - '.$this->Title : '') ?></title>

	<link rel="stylesheet" type="text/css" href="/css/reset.css" />
	<link rel="stylesheet" type="text/css" href="/css/debug.css" />
	<?= $this->GetStyleSheets() ?>

	<script type="text/javascript" src="/js/lib/jquery.min.js"></script>
	<script type="text/javascript" src="/js/debug.js"></script>
	<?= $this->GetJSFiles() ?>

	<?= $this->GetStyles() ?>
</head>
<body class="debug-page">
	<nav id="menu"></nav>
	<section class="page-holder">
		<div class="page">
			<?= $this->GetContent('default') ?>
		</div>
	</section>
</body>
</html>